AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - lib/**/*

Documentation:
  Enabled: false

LineLength:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
