AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - lib/**/*

Documentation:
  Enabled: false

LineLength:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Naming/RescuedExceptionsVariableName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
